### ISSUE TITLE
library cgi

### ISSUE THREAD

**Issue by winterwolf45** [paulheider/kiki-re#5]
hi thanks for this project 
i have this error :
AttributeError: module 'cgi' has no attribute 'escape'
after i search I understood this library removed on python 3 and need
and this my errors:
kiki.py:66: DeprecationWarning: NewId() is deprecated
  ID_EVALUATE = ni()
kiki.py:67: DeprecationWarning: NewId() is deprecated
  ID_NOTEBOOK = ni()
kiki.py:68: DeprecationWarning: NewId() is deprecated
  ID_HELPCOMBOBOX = ni()

(kiki.py:299268): Gtk-CRITICAL **: 09:58:58.155: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(kiki.py:299268): Gtk-CRITICAL **: 09:58:58.155: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(kiki.py:299268): Gtk-CRITICAL **: 09:58:58.155: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
Traceback (most recent call last):
  File "kiki.py", line 521, in evaluate
    output.append(self.showmatches())
  File "kiki.py", line 616, in showmatches
    html.append(self.htmlize(match.string[prevmatchend:match.start()]))
  File "kiki.py", line 539, in htmlize
    result = cgi.escape(text)
AttributeError: module 'cgi' has no attribute 'escape'

**Comment by uli99** [comment]
Hi,
I had the same problem and the solution seems to be to add "import html" under "import cgi" and then change "cgi.escape" to "html.escape"
